appsody/website

src/components/head.js
Add meta search tags to the header.
=> Add search meta tags to the header

src/pages/index.js, src/styles/main.css
fixes: https://github.com/appsody/website/issues/39
=> index: fix first image to be centered on medium devices

src/styles/main.css
fixes: https://github.com/appsody/website/issues/43
=> docs page: adding scroll on pre and code tags

package-lock.json, package.json, src/components/docNavbar.js, src/components/navbar.js, src/styles/main.css
fixes: https://github.com/appsody/website/issues/47
=> navbar: hamburger menu not collapsing fixed

src/components/docNavbar.js, src/components/navbar.js, src/components/navbarContent.js, src/styles/main.css, src/templates/docTemplate.js
=> Navbar: duplication removed

.github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, content/docs/overview.md, content/docs/stacks/create-or-modify.md, content/docs/stacks/stacks-overview.md
Adding community docs to the website/docs repo
#issue-number
=> community: add community docs

content/docs/getting-started/installation.md
I have added Xcode as a prereq for macOS installation
#issue-number: https://github.com/appsody/website/issues/68
=> docs-installation: Xcode listed as prereq for macOS

content/docs/stacks/stacks-overview.md
Update link to point to the location of new technical-requirements.md in stacks repo
#issue-number
=> docs-overview: update requirements link

content/docs/getting-started/installation.md, content/docs/using-appsody/building-and-deploying.md, content/docs/using-appsody/installing-knative-locally.md
Moving the last 2 PRs from docs into the website. The docs repo is now archived.
=> doc: add docs from appsody/docs

DEVELOPMENT.md, package-lock.json
fixes: https://github.com/appsody/website/issues/40
=> doc: add how to develop and test

package-lock.json, src/pages/index.js
Added swift stack tile
Fixes: #82
=> index: add swift tile

content/docs/using-appsody/building-and-deploying.md
=> building-and-deploying.md: fixed Installing Knative Locally link

content/docs/overview.md, content/docs/sidebar.yaml, content/docs/using-appsody/initializing-project.md
fixes: https://github.com/appsody/website/issues/76
=> doc: Renamed Creating Projects to Initialize Projects.

src/components/navbarContent.js, src/styles/main.css
Added a tutorials link in the navbar
Added styles for mobile to accommodate the extra link on `/docs` 
fixes: https://github.com/appsody/website/issues/80
=> navbarContent: add tutorials link

content/docs/using-appsody/cli-commands.md, package-lock.json
Scanned through cli-commands.md and updated the default path to a more accurate path.
https://github.com/appsody/stacks/issues/50
#issue-number
50
=> Fixed config to accurate path

content/docs/sidebar.yaml
Fix sidebar showing old documentation
=> config: fix sidebar showing old doc

src/components/navbarContent.js
Opens a new tab when navigating to the external tutorial page.
=> navbarContent: open new tab when going to tutorials

package.json
`gatsby build` doesn't do a clean build so we now run `gatsby clean` first to force this.
=> config: add gatsby clean to deploy command

content/docs/using-appsody/installing-knative-locally.md
Updating the KNative version to use the latest version.
fixes: #91
=> docs: bump knative version

content/docs/stacks/create-or-modify.md
Introduced a heading for point 1 of 'Creating a Stack' to keep the page format consistent.
https://github.com/appsody/website/issues/95
=> Temporary fix for formatting issue on 'Creating Stacks' page.

content/docs/overview.md
Changed opening paragraph on https://appsody.dev/docs to:
"Our aims were to simplify the experience for developers, relieving them of full-stack expertise and responsibilities, and allowing them to focus on their application code development activities; enabling architects to curate an opinionated set of technologies - configurable, reusable and already infused with cloud native capabilities, making them seamlessly available to application developers."
https://github.com/appsody/website/issues/90
=> Improved ambiguous description in the docs page

.travis.yml
Add travis to handle website deploys on merges to master
fixes: https://github.com/appsody/website/issues/100
=> build: add travis to deploy to gh-pages

content/docs/using-appsody/installing-knative-locally.md
=> installing-knative-locally.md: fixed small typo

content/docs/getting-started/quick-start.md
Appsody build fails if you have a uppercase letter in your directory, this pr adds a note at the create directory step
=> docs: add note to getting started ref lowercase name

content/docs/using-appsody/building-and-deploying.md
Documented the new `-t <tag>` option for `appsody build` and the fact that we lowercase the project name to avoid problems with Docker tagging.
https://github.com/appsody/appsody/issues/73
=> Updated build with addition of -t and lowercasing

gatsby-node.js
Added a redirect for `/tutorials` to medium
=> config: add redirect for /tutorials

content/docs/getting-started/quick-start.md
This line was added in as a temporary fix till we released the 0.2.5 version of the cli.
#issue-number
=> docs: removing temp fix

.github/PULL_REQUEST_TEMPLATE.md
Fixed a broken link in the PR template that leads to a 404 error when finding more info to test locally.
Fixes: https://github.com/appsody/website/issues/114
#issue-number
=> pr template: fixed broken link

content/docs/using-appsody/cli-commands.md
Removes front matter from the CLI reference. The website no longer uses this front matter
=> docs: remove redundant front matter

NOTICE.md, src/pages/index.js
Updated titles and descriptions for stacks to match proper names
n/a
=> docs, index: update title, desc of stacks

src/components/docSidebar.js, src/styles/main.css
Current page in docs is highlighted on docs sidebar
Fixes #106
=> components: changed current page to be highlighted in docSidebar

content/docs/using-appsody/cli-commands.md
This is part of the CLI Release Process where the generated Doc changes will be merged in.
=> Generated cli-commands.md changes for Travis build: 271

content/docs/getting-started/installation.md
Fixed a few links pointing to the quick start guide
=> docs: fix broken quick start links

content/docs/getting-started/installation.md, content/docs/using-appsody/building-and-deploying.md
Restructured installation doc to separate install/upgrade/uninstall into sections. Added steps to upgrade CLI. All other file changes are small, to keep the "Notes:" consistent.
Fixes https://github.com/appsody/appsody/issues/42
=> docs: added steps to upgrade CLI

content/docs/getting-started/installation.md
Updating `installation.md`
#issue-number
=> docs: updating installation docs

content/docs/faq.md, gatsby-config.js
- Updated the config for `remark` to fix https://github.com/appsody/website/issues/42
- Updated FAQ doc to use new configuration 
fixes: https://github.com/appsody/website/issues/42
=> config: update remark settings

content/docs/using-appsody/installing-knative-locally.md
Fixed regression from https://github.com/appsody/website/pull/145
refs: https://github.com/appsody/website/pull/145
fixes: https://github.com/appsody/website/issues/150
=> docs: fix formatting on knative docs

src/styles/main.css
Fixed linking so that start of that section is underneath the navbar and visible.
Fixes: https://github.com/appsody/website/issues/135
=> styles: fixed linking within document

content/docs/faq.md, content/docs/getting-started/installation.md, content/docs/getting-started/quick-start.md, content/docs/overview.md, content/docs/stacks/create-or-modify.md, content/docs/stacks/stack-structure.md, content/docs/stacks/stacks-overview.md, content/docs/using-appsody/building-and-deploying.md, content/docs/using-appsody/cli-commands.md, content/docs/using-appsody/initializing-project.md, content/docs/using-appsody/installing-knative-locally.md, content/docs/using-appsody/local-development.md
- Added `title` front matter to the docs to be used with the search bar - coming soon
refs: https://github.com/appsody/website/issues/52
cc: @Bazif-Khan
=> docs: add title front matter to be used with the search

content/docs/using-appsody/cli-commands.md
Please include this document in the website as it updates the CLI help text for release 0.3.0
=> Travis build: 365 merge request for 0.3.0 release of CLI

content/docs/overview.md, content/docs/stacks/create.md, content/docs/stacks/stacks-overview.md
=> links: broken links fixed

src/components/docSidebar.js
Added unique key prop for each child in a list
Fixes: https://github.com/appsody/website/issues/165
=> components: added unique key prop

content/docs/getting-started/installation.md
Added ink to appsody-controller
Fixes: #140
=> doc: add link to appsody-controller

content/docs/getting-started/installation.md
Removed space in doc link
#issue-number
=> doc: removed space

DEVELOPMENT.md
Included gatsby clean cmd in DEVELOPMENT.md doc
Fixes: #172
=> docs: added gatsby clean command

src/components/docSidebar.js
=> docSidebar: Docs menu close when clicked on the link in mobile view

CONTRIBUTING.md
Fix Code of conduct from (broken) relative URL.
#issue-number
=> Contributing.MD: fix code of conduct URL

CONTRIBUTING.md
Fixes a few broken links in the contributing guildlines
=> docs: fix broken links

src/styles/main.css
Added margin below tables to separate them from any content below.
=> styles: add margin to bottom of tables

content/docs/stacks/stack-structure.md
Updated the keys that should be in a `stack.yaml`
=> docs: update stack.yaml contents

content/docs/sidebar.yaml, content/docs/stacks/build-and-test.md, content/docs/stacks/create.md, content/docs/stacks/modify.md, content/docs/stacks/run-locally.md
=> docs: Docs for local development using build scripts

content/docs/stacks/build-and-test.md, content/docs/stacks/stack-structure.md
fixes: https://github.com/appsody/stacks/issues/215
=> docs: .appsody-config removed from docs

content/docs/stacks/stack-structure.md
=> Stack-structure doc: extra line removed from doc

content/docs/using-appsody/building-and-deploying.md
Added information on how to delete a local deployment
#issue-number
=> docs: add deploy delete info

content/docs/stacks/build-and-test.md, content/docs/using-appsody/local-development.md
Signed-off-by: Erin Schnabel <schnabel@us.ibm.com>
#issue-number
=> Update local stack development & run command description

content/docs/faq.md
=> FAQ: add .appsody hidden folder

src/components/tile.js, src/components/tileGrid.js, src/data/indexes/sample-index.yaml, src/styles/main.css
Fixes: https://github.com/appsody/website/issues/190
=> Tile: Long description in stack tile is truncated

content/docs/using-appsody/building-and-deploying.md
=> CLI appsody deploy: documented operator, updated refs to Knative

content/docs/using-appsody/cli-commands.md
This is an update of the CLI-commands.md document due to the changes in the 0.4.1 release of Appsody CLI.
=> Travis build: 0.4.1572

content/docs/stacks/build-and-test.md
=> docs: added instructions for running prefetch

content/docs/stacks/stack-structure.md
The current description of stack structure was somewhat terse. More importantly, it didn't really give the reader the context in which the stack operates at run/build time - and the requirements therefore on the stack. This PR enhances these descriptions - and, by design, includes many more details about what happens at run/build time, and the interaction between the client and controller, in order to provide this context.
Fixes #187
=> Improve description of stack structure and requirements

content/docs/stacks/build-and-test.md
=> docs: removed prefetch step

content/docs/stacks/stack-structure.md
Update stack structure to include the necessary deploy files
Fixes: #217
=> docs: updated stack structure

content/docs/stacks/create.md
=> docs: fixed typo

content/docs/using-appsody/cli-commands.md
Updates for cli-commands.md due to auto generation of help text.
Flag for buildah.
=> Travis build: 0.4.2584

content/docs/using-appsody/building-and-deploying.md
As discussed in issue https://github.com/appsody/appsody/issues/242
#236
=> WIP: Appsody deploy: RBAC documentation

content/docs/using-appsody/building-and-deploying.md
This PR contains documentation on how to use the createKnativeService: true setting.
Fixes #238.
=> Describe the use of the createKnative element, typos

content/docs/using-appsody/cli-commands.md
PR for new CLI release
#issue-number
=> Travis build: 0.4.5797

content/docs/faq.md, content/docs/getting-started/installation.md, content/docs/getting-started/quick-start.md, content/docs/overview.md, content/docs/stacks/build-and-test.md, content/docs/stacks/create.md, content/docs/stacks/environment-variables.md, content/docs/stacks/modify.md, content/docs/stacks/stack-structure.md, content/docs/stacks/stacks-overview.md, content/docs/using-appsody/building-and-deploying.md, content/docs/using-appsody/cli-commands.md, content/docs/using-appsody/initializing-project.md, content/docs/using-appsody/installing-knative-locally.md, content/docs/using-appsody/local-development.md, gatsby-node.js, src/components/search.js, src/templates/docTemplate.js
fixes: https://github.com/appsody/website/issues/264
=> Slugs: Creating slugs for pages so there is no need to provide url path in front matter of docs

content/docs/using-appsody/building-and-deploying.md
Added a section that describes the behavior some users have observed when running `appsody deploy` multiple times, and no application changes are published to the cluster. Added steps to ensure the latest changes are published.
Fixes #246
=> Added section on deploying latest changes to K8S through `appsody deploy`

content/docs/getting-started/installation.md
Describes the new behavior of the Windows installer with regard to handling the Path.
Fixes #266
=> Updated Win install/uninstall to reflect handling of Path

content/docs/using-appsody/cli-commands.md
=> Travis build: 0.4.6923

content/docs/using-appsody/cli-commands.md
This releases updates are contained in this file.
=> Updated cli-doc for Travis build: 0.4.71137

content/docs/using-appsody/building-and-deploying.md
=> building and deploying: fixed broken link

content/docs/using-appsody/cli-commands.md
=> Travis build: 0.4.8-1324

src/components/docHead.js
Adds a script to the doc head that was missing, as it went in just before my original PR was merged.
Fixes issue #346
=> Add missing script to doc head

content/docs/using-appsody/cli-commands.md
=> Travis build: 0.5.0-1614

content/docs/sidebar.yaml, content/docs/stacks/package.md, content/docs/stacks/publish.md
Signed-off-by: Steve Groeger <GROEGES@uk.ibm.com>
#issue-number
=> Add new web page for the add-to-repo CLI command

src/styles/main.css
Adds styling for bullet point lists, which at the moment, don't have any styling at all.
#387
=> Added bulletpoint styling

content/docs/docker-windows-aad.md, content/docs/getting-started/installation.md, content/docs/stacks/modify.md, content/docs/stacks/package.md, content/docs/stacks/publish.md, content/docs/stacks/stack-structure.md, content/docs/using-appsody/building-and-deploying.md, src/styles/main.css
fixes: https://github.com/appsody/website/issues/367
=> Styling for Blockquotes for notes in docs

src/components/navbar.js
better link on medium which shows all articles
Fixes https://github.com/appsody/website/issues/399
=> Update navbar tutorials link

src/components/SEO.js
Changed the Twitter descriptions to be smaller so they fit inside a card without going off the end.
#334
=> updated SEO with a shorter description for Twitter cards

src/styles/main.css, src/styles/sidebar.module.css
Fixes the scrolling issue when clicking an anchor link (like a title).
#396 
@ddunn2 for his code, but he's out and his code was conflicting with changes that went in Friday and we want the change in ASAP and he's out for a few days 😭 so this PR is to make the fix ASAP
=> Fixed padding for anchor links to scroll correctly

content/docs/using-appsody/cli-commands.md
=> Travis build: 0.5.1-1878

content/docs/using-appsody/building-and-deploying.md
Updating the deploy and build docs for the next release of the CLI. 
Removing documentation related to `generate-only`
DO NOT MERGE.
#348 
#422 
#338
=> Update deploy docs

content/docs/using-appsody/cli-commands.md
=> Travis build: 0.5.3-2008

content/docs/stacks/modify.md
Added `image-registry` to the table of available templating variables
This should go in when https://github.com/appsody/appsody/pull/750/files gets merged
=> docs: added registry templating variable

content/docs/stacks/ci-scripts.md, content/docs/stacks/develop.md, content/docs/stacks/lifecycle.md, content/docs/stacks/package.md, content/docs/stacks/publish-ci-scripts.md, content/docs/stacks/publish.md, content/docs/stacks/test.md
=> fixed links and added mount issue

src/styles/main.css
=> fixes image placement on homepage

src/components/tileGrid.js
=> Stacks: Incubator Stacks are displayed first on the page (Sorting by Incubator Stacks) 

DEVELOPMENT.md, gatsby-node.js
As we're using a gatsby plugin to redirect content we need some usage instructions on how to add redirecting for contributors. 
#374
=> Adds redirecting instructions to the development guidelines

src/styles/main.css, src/styles/sidebar.module.css
=> Docs Sidebar: Scroll capability added on docs sidebar

content/docs/stacks/develop.md, content/docs/using-appsody/cli-commands.md
Change references to text referencing sample stack created when using `appsody stack create` to new `incubator/starter` stack
Fixes appsody [832 issue](https://github.com/appsody/appsody/issues/832)
=> [Do not merge until CLI release] Changed text to updated stack create command

src/styles/main.css
Tones down the colour of an active card to be a less vibrant pink in dark mode
=> Updated colouring of active cards in Dark Mode

package.json, src/components/tile.js
Updates the date format for the updated cards on the homepage to be more readable
#477
=> Update Date format on Recently Updated cards

content/docs/overview.md
=> Fix link to contributing information

content/docs/stacks/stacks-overview.md
Added to stable criteria:
- stack should not use single file mounts
- stack should document how to manage dependency inclusions
=> docs: add to stack stable criteria

content/docs/using-appsody/initializing-project.md
Describe the `--stack-registry` flag and why a user might specify it.
Fixes #421
=> Add stack-registry to initializing projects

content/docs/using-appsody/cli-commands.md
=> Travis build: 0.5.7-2391

content/docs/stacks/package.md, content/docs/stacks/publish.md
Include references of source code archives generated from stack package.
Changes from [PR](https://github.com/appsody/appsody/pull/856) 856.
#issue-number
=> Include references of source code archives to documentation

content/docs/stacks/publish.md
Documented how to use the `create_codewind_index.py` script to generate `.json` files from `.yaml` files
Related to #https://github.com/appsody/stacks/pull/669
=> docs: generation of json file

content/blogs/AutumnUpdate.md, content/blogs/BuildingCloudNativeAppsWithAppsody.md
Edit blogs to fix broken links and fix default deployment options (as these have changed since the blog was published).
Fixes #504
=> Fix broken links and deployment default in blogs

content/docs/stacks/ci-scripts.md, content/docs/stacks/publish-ci-scripts.md, src/components/wideBlogPost.js, src/templates/blogTemplate.js
fixes: https://github.com/appsody/website/issues/474
=> Search: search results show a blank instead of the page title

DEVELOPMENT.md, content/docs/installing/macos.md, content/docs/installing/rhel.md, content/docs/installing/ubuntu.md, content/docs/installing/windows.md
=> docs: replace Quick Start refs with Getting Started

content/docs/stacks/stacks-overview.md
Added 'do not pull in version changes' to stable criteria
=> docs: add 'do not pull in version changes' to stable criteria

content/docs/cli-commands.md
=> Travis build: 0.6.0-2833

content/tutorials/ServerSideSwiftDevelopInXcode.md
Fixes a typo in the title for the Swift tutorial.
#issue-number
=> fixed title typo

content/tutorials/BuildANewCloudNativeExpressAppWithAppsody.md
Removes an errant ' from the end of the tutorial title
=> Remove errant ' from tutorial title

content/docs/faq.md, content/docs/stacks/develop.md, content/docs/stacks/lifecycle.md
=> update environment doc links

content/tutorials/open-liberty-stack-tutorial.md
Tutorial does not show approx timing for completion.
All missing front matter now added.
Signed-off-by: Sue Chaplain <sue_chaplain@uk.ibm.com>
#issue-number
=> Add missing frontmatter

src/components/topDownloadedTileGrid.js
=> Homepage: Removed Deprecated Stacks From The Most Popular Section

content/docs/cli-commands.md
=> Travis build: 0.6.3-2934

content/docs/cli-commands.md, content/docs/sidebar.yaml
Rename "CLI Reference" doc to "CLI Commands"
https://github.com/appsody/appsody/pull/1006
=> rename "CLI Reference" doc to "CLI Commands"

content/tutorials/ServerlessRust.md
The indentation is causing the code snippets on the in the IBM Cloud section to render incorrectly.
See https://appsody.dev/tutorials/ServerlessRust/#deploy-to-knative-on-ibm-cloud
=> remove tabs to correct formatting

content/docs/cli-commands.md
=> Travis build: 0.6.5-2942

README.md
Update README to reflect end of Appsody development
=> Update README to reflect end of Appsody development
