appsody/website

DEVELOPMENT.md
content/docs/getting-started/installation.md
content/docs/getting-started/quick-start.md
content/docs/overview.md
content/docs/sidebar.yaml
content/docs/stacks/create-or-modify.md
content/docs/stacks/stack-structure.md
content/docs/stacks/stacks-overview.md
content/docs/using-appsody/building-and-deploying.md
content/docs/using-appsody/cli-commands.md
content/docs/using-appsody/creating-project.md
content/docs/using-appsody/installing-knative-locally.md
content/docs/using-appsody/local-development.md
src/components/docSidebar.js

Switch to a yaml file to define the structure of the docs sidebar. 
This allows us to:
- easily control the weighting of both sections and their contents.
- have sections without a title
- what documentation is shown in the sidebar and what is hidden
fixes: https://github.com/appsody/website/issues/46

docSidebar, docs: switch to using a yaml file to define sidebar format

---

content/docs/using-appsody/building-and-deploying.md

Found a few small typos https://appsody.dev/docs/using-appsody/building-and-deploying
Fixes: Changed "The appsody CLI creates a Knative Serving manifest file named ```appsody-service-nnnnnn.yaml```, where is a random numerical value." to "where nnnnnn is a random numerical value".

docs: fixed small typos in building and deploying page

---

RELEASE.md

Adds the release process for deploying the website with the latest documentation
fixes: https://github.com/appsody/website/issues/54

docs: add release process for website and docs

---

src/styles/main.css

Limited the highlight for active page only on links in the docs sidebar
refs: https://github.com/appsody/website/pull/125

styles: limit active link highlight to the docs sidebar

---

content/docs/stacks/create-or-modify.md

The 'Creating a stack' page provides steps to clone the sample stack. The url it uses points at the old docs repo.
This PR updates the clone url as well as the directory the user should then change into, to match the new location in the stacks repo.

docs: update clone url of sample-stack

---

content/docs/stacks/stack-structure.md

Fixes typo referencing `image` instead of `stack`

docs: fix typo in stack structure

---

src/styles/main.css

The description in the tiles look a little too close to the edge, suggesting we add some padding to make the text look less cramped. For example take a look at the Quarkus description..
**before:**
**after:**

website: add padding to tiles

---

content/docs/getting-started/installation.md

Added to Linux installation instructions to mention that if a user would like to download a pre-built binary, they also need to download the appsody-controller
Fixes: #140

docs:added appsody-controller to installation

---

src/styles/main.css

Reintroduced a fix to pin the footer to the bottom of the page for short docs.
Fixes: #161

docs: pinned footer to bottom of page regardless of page height

---

content/docs/stacks/create.md
content/docs/stacks/modify.md

Fixes broken links. `/docs/stacks/run-locally` -> `/docs/stacks/build-and-test`
fixes: https://github.com/appsody/website/issues/188

docs: fix links to build and test stacks page

---

content/docs/using-appsody/cli-commands.md

This updates the cli-commands.md file for release 0.4.0
We will fix the version name on the branch in next weeks release btw.
This was tested with gatsby develop.
Any edits will be made manually if changes are requested.

Travis build: Update CLI documentation for release 0.4.0

---

content/docs/faq.md

We are deprecating the v1 index, this will show users how they can fix the error that occurs when the CLI tries to read the v2 index.
fixes: https://github.com/appsody/appsody/issues/223

FAQ: add steps for configuring a new index

---

content/docs/stacks/build-and-test.md
content/docs/stacks/create.md
content/docs/stacks/stack-structure.md

- This PR removes the mentioning of the .appsody-config file during template creation. 
- Fixes some wording. 
- Adds LICENSE file to the file structure
fixes: https://github.com/appsody/website/issues/202

docs: remove mention of .appsody-config file

---

content/docs/stacks/stack-structure.md

We don't need this extra part of the dependency example - less is more when you are learning!
Fixes #224

Clarify dependency example in stack-structure be removing extraneous line

---

content/docs/sidebar.yaml

Make the stack environment variable page easier to find, by adding it to the sidebar.
Fixes #221

Add environment variable page to sidebar

---

content/docs/sidebar.yaml
content/docs/stacks/stacks-overview.md

This logically probably sits below the "Stack Overview" item in the sidebar, and should also be referenced from the overview.
Fixes: #223

Improve visibility of stack-structure doc

---

content/docs/stacks/build-and-test.md
content/docs/using-appsody/initializing-project.md

We have renamed the template published for nodejs-express from 'skaffold' to 'scaffold' so that it uses proper spelling. The updated stack has been release this morning. 
This PR updates doc references to match the change.
Signed-off-by: Neeraj Laad <neeraj.laad@gmail.com>

nodejs-express: rename template

---

content/docs/stacks/stacks-overview.md

This PR adds a table to the [Stack Overview](https://appsody.dev/docs/stacks/stacks-overview/) page of the Appsody docs. The table shows URLs of the official Appsody released stacks that can be added to the Appsody CLI. By default the Appsody CLI only sets up the incubator stack, there is no mention of the experimental stack URL. With [82 releases](https://github.com/appsody/stacks/releases) in the Appsody repo itself a more obvious way to add/remove official repos should be surfaced in the docs.
The `Stack Overview` page felt like the right spot for this information, but it could easily have gone in [Local Development](https://appsody.dev/docs/using-appsody/local-development). I'm happy to make any changes the reviewers suggest.
Fixes: #285

add URLs for official stacks

---

src/styles/main.css

Adds some spacing to the headers with the docs to create a better sense of separation. This is a short term bandaid as we will address the style of the docs again in #257
#257

Add some spacing between sections in docs

---

src/pages/index.js
src/styles/main.css
src/styles/mobileNav.module.css

Fixes an issue where the new mobile navigation bar overlaps the footer in mobile mode. Adds some padding for the content of the page too.
Fixes #325

fixes: mobile nav overlapping footer

---

content/docs/faq.md

The current FAQ page is returning a page-not-found (http status 404) response when the user clicks on "...please follow the instructions in the page Appsody and Docker Desktop on Windows 10."
None.

Fix http status 404 for Windows 10 FAQ

---

src/styles/mobileNav.module.css

The homebar on newer iPhones requires some safe areas to be used, or else content can scroll too low and be hard to tap. This PR adds that safe area to the bottom menu. The change will only appear on iPhones running iOS 11+ and with a homebar (iPhone X onwards). Makes no changes in Chrome.
#391

Add safe area to iPhone to avoid home bar overlapping nav menu

---

content/docs/getting-started/installation.md

- [x ] commit message follows [commit guidelines](https://github.com/appsody/website/blob/master/CONTRIBUTING.md#commit-message-guidelines).
- [ x] website builds and runs in production - for information on how to test locally go [here](https://github.com/appsody/website/blob/master/DEVELOPMENT.md).
Removed the remaining reference to the controller bind mount - now obsolete.
#393

Removed reference to controller bind mount

---

src/styles/main.css

Changes the design for inline code blocks to be bold and a different font compared to the current style of being grey boxes, which can be hard to see on some table rows.

New styling for inline code blocks (bold, new font)

---

content/docs/getting-started/quick-start.md
content/docs/stacks/modify.md

The quickstart guide was using a bold text section for displaying the tip at the bottom of the page. This PR fixes it to use the new block quote style introduced recently.

Fixes tips in quickstart to use the new quote styling

---

content/docs/using-appsody/building-and-deploying.md

Added back the word note as it was removed from the Doc in a previous refactoring and styling PR
#419

added word note back into doc

---

content/docs/faq.md
content/docs/stacks/create.md
content/docs/stacks/package.md
content/docs/stacks/publish.md
package.json

If a user is expected to copy some code into their terminal, the code should not be inline with the rest of the normal text. Referencing a command can stay inline though, this PR just moved the code that a user is expected to put into their terminal onto their own lines to they get the code block styling.
#409

Moved user exectuable code into their own code blocks

---

DEVELOPMENT.md
content/docs/glossary.md
content/docs/sidebar.yaml
src/components/doc.js
src/styles/main.css
src/templates/docTemplate.js

Adds a glossary page to the site without MDX support, so the website will work as it always has and we can merge the Glossary page in without needing to fix the CLI reference page breaking React components with unclosed HTML tags (https://github.com/appsody/appsody/issues/761).
#282 #272

 Glossary page (No MDX support)

---

src/styles/main.css

Dividers stayed dark in dark mode and therefore were too hard to see, this PR changes them to make them the correct colour in dark mode.

Make dividers look correct in dark mode

---

content/docs/using-appsody/building-and-deploying.md

This functionality was removed in commit https://github.com/appsody/appsody/commit/41ff13d15f5104dede1ee13a20307bfaa089b42f
#issue-number

Remove knative deploy option because it no longer exists

---

content/docs/glossary.md

Add Appsody controller and Appsody operator definitions to the Glossary.
Adds two more Appsody terms to the Glossary.
Issue #272

Add operator and controller to glossary.md

---

content/docs/using-appsody/building-and-deploying.md

Fixes the issue https://github.com/appsody/appsody/issues/887.
The Tekton pipeline example doesn't use Knative serving any more.  Plus the prerequisites are all listed in tekton-example README, plus `appsody deploy --generate-only` has been replaced (as suggested) with `appsody build`.

Update docs to match Tekton example

---

content/docs/stacks/publish.md

The example in the publishing stacks documentation doesn't mention the `image-registry` flag so users will end up with their stack images in `dev.local` which they might not want. 
Fixes #509

Document image-registry flag in publishing stacks doc

---

content/docs/using-appsody/initializing-project.md

Updated the "Initializing project" article to include the java-openliberty stack in `appsody list` output.

Add java-openliberty stack to screenshots

---

content/blogs/AutumnUpdate.md
content/blogs/BohemianAppsody.md

Removed references of "head over to Appsody" from blogs as we have migrated blogs to be directly on the website

remove references of 'head over to Appsody' from blogs

---

content/docs/faq.md
content/docs/installing/installing-appsody.md
content/docs/using-appsody/building-and-deploying.md

Mentions the `appsody-buildah` image used in the tekton example. I'm not sure how much explanation needs to be done here as the README in the repo goes into further detail.
Fixes: #539

Add reference to appsody buildah image under tekton section

---

src/styles/main.css

Italics that were inline in text blocks were being rendered as if they were the information/quotes below images and were centered and spaced out from the rest of the paragraph. This fixes that.
#issue-number

Fixed italics in tutorials that arent part of images

---

content/tutorials/ServerSideSwiftDevelopInXcode.md

Fixed the typo in the front matter of the swift tutorial
#issue-number

Fixed a Swift tutorial typo in the frontmatter

---

src/components/navbar.js

This PR removes the Twitter and Slack links from the nav bar as these accounts are no longer active.

Remove twitter and slack icons
